*&---------------------------------------------------------------------*
*& Report ZBRCIAM
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBRCIAM.

DATA: lt_data type table of ZBRC_IAM.

"read current timestamp
GET TIME STAMP FIELD DATA(zv_tsl).

"fill internal table
lt_data = VALUE #(

  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE41' approver_email ='approver41@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE41' approver_email ='approver41@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE41' approver_email ='approver41@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE41' approver_email ='approver41@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE42' approver_email ='approver42@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE42' approver_email ='approver42@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE42' approver_email ='approver42@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE42' approver_email ='approver42@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE43' approver_email ='approver43@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE43' approver_email ='approver43@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE43' approver_email ='approver43@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE43' approver_email ='approver43@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE44' approver_email ='approver44@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE44' approver_email ='approver44@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE44' approver_email ='approver44@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE44' approver_email ='approver44@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE45' approver_email ='approver45@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE45' approver_email ='approver45@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE45' approver_email ='approver45@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE45' approver_email ='approver45@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE46' approver_email ='approver46@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE46' approver_email ='approver46@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE46' approver_email ='approver46@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE46' approver_email ='approver46@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE47' approver_email ='approver47@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE47' approver_email ='approver47@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE47' approver_email ='approver47@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE47' approver_email ='approver47@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE48' approver_email ='approver48@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE48' approver_email ='approver48@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE48' approver_email ='approver48@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE48' approver_email ='approver48@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE49' approver_email ='approver49@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE49' approver_email ='approver49@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE49' approver_email ='approver49@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE49' approver_email ='approver49@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE50' approver_email ='approver50@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE50' approver_email ='approver50@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE50' approver_email ='approver50@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE50' approver_email ='approver50@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE51' approver_email ='approver51@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE51' approver_email ='approver51@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE51' approver_email ='approver51@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE51' approver_email ='approver51@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE52' approver_email ='approver52@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE52' approver_email ='approver52@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE52' approver_email ='approver52@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE52' approver_email ='approver52@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE53' approver_email ='approver53@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE53' approver_email ='approver53@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE53' approver_email ='approver53@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE53' approver_email ='approver53@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE54' approver_email ='approver54@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE54' approver_email ='approver54@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE54' approver_email ='approver54@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE54' approver_email ='approver54@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE55' approver_email ='approver55@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE55' approver_email ='approver55@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE55' approver_email ='approver55@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE55' approver_email ='approver55@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE56' approver_email ='approver56@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE56' approver_email ='approver56@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE56' approver_email ='approver56@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE56' approver_email ='approver56@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE57' approver_email ='approver57@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE57' approver_email ='approver57@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE57' approver_email ='approver57@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE57' approver_email ='approver57@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE58' approver_email ='approver58@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE58' approver_email ='approver58@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE58' approver_email ='approver58@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE58' approver_email ='approver58@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE59' approver_email ='approver59@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE59' approver_email ='approver59@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE59' approver_email ='approver59@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE59' approver_email ='approver59@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE60' approver_email ='approver60@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE60' approver_email ='approver60@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE60' approver_email ='approver60@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE60' approver_email ='approver60@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE61' approver_email ='approver61@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE61' approver_email ='approver61@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE61' approver_email ='approver61@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE61' approver_email ='approver61@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE62' approver_email ='approver62@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE62' approver_email ='approver62@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE62' approver_email ='approver62@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE62' approver_email ='approver62@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE63' approver_email ='approver63@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE63' approver_email ='approver63@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE63' approver_email ='approver63@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE63' approver_email ='approver63@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE64' approver_email ='approver64@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE64' approver_email ='approver64@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE64' approver_email ='approver64@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE64' approver_email ='approver64@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE65' approver_email ='approver65@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE65' approver_email ='approver65@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE65' approver_email ='approver65@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE65' approver_email ='approver65@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE66' approver_email ='approver66@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE66' approver_email ='approver66@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE66' approver_email ='approver66@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE66' approver_email ='approver66@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE67' approver_email ='approver67@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE67' approver_email ='approver67@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE67' approver_email ='approver67@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE67' approver_email ='approver67@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE68' approver_email ='approver68@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE68' approver_email ='approver68@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE68' approver_email ='approver68@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE68' approver_email ='approver68@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE69' approver_email ='approver69@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE69' approver_email ='approver69@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE69' approver_email ='approver69@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE69' approver_email ='approver69@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE70' approver_email ='approver70@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE70' approver_email ='approver70@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE70' approver_email ='approver70@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE70' approver_email ='approver70@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE71' approver_email ='approver71@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE71' approver_email ='approver71@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE71' approver_email ='approver71@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE71' approver_email ='approver71@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE72' approver_email ='approver72@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE72' approver_email ='approver72@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE72' approver_email ='approver72@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE72' approver_email ='approver72@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE73' approver_email ='approver73@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE73' approver_email ='approver73@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE73' approver_email ='approver73@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE73' approver_email ='approver73@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE74' approver_email ='approver74@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE74' approver_email ='approver74@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE74' approver_email ='approver74@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE74' approver_email ='approver74@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE75' approver_email ='approver75@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE75' approver_email ='approver75@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE75' approver_email ='approver75@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE75' approver_email ='approver75@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE76' approver_email ='approver76@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE76' approver_email ='approver76@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE76' approver_email ='approver76@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE76' approver_email ='approver76@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE77' approver_email ='approver77@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE77' approver_email ='approver77@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE77' approver_email ='approver77@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE77' approver_email ='approver77@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE78' approver_email ='approver78@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE78' approver_email ='approver78@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE78' approver_email ='approver78@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE78' approver_email ='approver78@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE79' approver_email ='approver79@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE79' approver_email ='approver79@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE79' approver_email ='approver79@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE79' approver_email ='approver79@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='ABAP' company_code ='DE80' approver_email ='approver80@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP A4H' request_context_value ='WebDynpro' company_code ='DE80' approver_email ='approver80@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='JAVA' company_code ='DE80' approver_email ='approver80@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )
  ( client ='001' request_context_type ='SAP BTP' request_context_value ='SAPUI5' company_code ='DE80' approver_email ='approver80@bestruncorp.onmicrosoft.com' local_last_changed = zv_tsl last_changed = zv_tsl )

).

"Delete possible entries; insert new entries
DELETE FROM ZBRC_IAM.

INSERT ZBRC_IAM from table @lt_data.

WRITE: / 'Entries created:', sy-dbcnt.